//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 The Kubellm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	url "net/url"
	unsafe "unsafe"

	clusterkubellmio "github.com/kubellm-io/kubellm/pkg/apis/cluster.kubellm.io"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEnablement)(nil), (*clusterkubellmio.APIEnablement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_APIEnablement_To_clusterkubellmio_APIEnablement(a.(*APIEnablement), b.(*clusterkubellmio.APIEnablement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.APIEnablement)(nil), (*APIEnablement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_APIEnablement_To_v1alpha1_APIEnablement(a.(*clusterkubellmio.APIEnablement), b.(*APIEnablement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIResource)(nil), (*clusterkubellmio.APIResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_APIResource_To_clusterkubellmio_APIResource(a.(*APIResource), b.(*clusterkubellmio.APIResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.APIResource)(nil), (*APIResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_APIResource_To_v1alpha1_APIResource(a.(*clusterkubellmio.APIResource), b.(*APIResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AllocatableModeling)(nil), (*clusterkubellmio.AllocatableModeling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AllocatableModeling_To_clusterkubellmio_AllocatableModeling(a.(*AllocatableModeling), b.(*clusterkubellmio.AllocatableModeling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.AllocatableModeling)(nil), (*AllocatableModeling)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_AllocatableModeling_To_v1alpha1_AllocatableModeling(a.(*clusterkubellmio.AllocatableModeling), b.(*AllocatableModeling), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Cluster)(nil), (*clusterkubellmio.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Cluster_To_clusterkubellmio_Cluster(a.(*Cluster), b.(*clusterkubellmio.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.Cluster)(nil), (*Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_Cluster_To_v1alpha1_Cluster(a.(*clusterkubellmio.Cluster), b.(*Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterList)(nil), (*clusterkubellmio.ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterList_To_clusterkubellmio_ClusterList(a.(*ClusterList), b.(*clusterkubellmio.ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ClusterList)(nil), (*ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ClusterList_To_v1alpha1_ClusterList(a.(*clusterkubellmio.ClusterList), b.(*ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterProxyOptions)(nil), (*clusterkubellmio.ClusterProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterProxyOptions_To_clusterkubellmio_ClusterProxyOptions(a.(*ClusterProxyOptions), b.(*clusterkubellmio.ClusterProxyOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ClusterProxyOptions)(nil), (*ClusterProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(a.(*clusterkubellmio.ClusterProxyOptions), b.(*ClusterProxyOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSpec)(nil), (*clusterkubellmio.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec(a.(*ClusterSpec), b.(*clusterkubellmio.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ClusterSpec)(nil), (*ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec(a.(*clusterkubellmio.ClusterSpec), b.(*ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterStatus)(nil), (*clusterkubellmio.ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus(a.(*ClusterStatus), b.(*clusterkubellmio.ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ClusterStatus)(nil), (*ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus(a.(*clusterkubellmio.ClusterStatus), b.(*ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalSecretReference)(nil), (*clusterkubellmio.LocalSecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LocalSecretReference_To_clusterkubellmio_LocalSecretReference(a.(*LocalSecretReference), b.(*clusterkubellmio.LocalSecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.LocalSecretReference)(nil), (*LocalSecretReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_LocalSecretReference_To_v1alpha1_LocalSecretReference(a.(*clusterkubellmio.LocalSecretReference), b.(*LocalSecretReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeSummary)(nil), (*clusterkubellmio.NodeSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeSummary_To_clusterkubellmio_NodeSummary(a.(*NodeSummary), b.(*clusterkubellmio.NodeSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.NodeSummary)(nil), (*NodeSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_NodeSummary_To_v1alpha1_NodeSummary(a.(*clusterkubellmio.NodeSummary), b.(*NodeSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceModel)(nil), (*clusterkubellmio.ResourceModel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceModel_To_clusterkubellmio_ResourceModel(a.(*ResourceModel), b.(*clusterkubellmio.ResourceModel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ResourceModel)(nil), (*ResourceModel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ResourceModel_To_v1alpha1_ResourceModel(a.(*clusterkubellmio.ResourceModel), b.(*ResourceModel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceModelRange)(nil), (*clusterkubellmio.ResourceModelRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceModelRange_To_clusterkubellmio_ResourceModelRange(a.(*ResourceModelRange), b.(*clusterkubellmio.ResourceModelRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ResourceModelRange)(nil), (*ResourceModelRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ResourceModelRange_To_v1alpha1_ResourceModelRange(a.(*clusterkubellmio.ResourceModelRange), b.(*ResourceModelRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceSummary)(nil), (*clusterkubellmio.ResourceSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceSummary_To_clusterkubellmio_ResourceSummary(a.(*ResourceSummary), b.(*clusterkubellmio.ResourceSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clusterkubellmio.ResourceSummary)(nil), (*ResourceSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clusterkubellmio_ResourceSummary_To_v1alpha1_ResourceSummary(a.(*clusterkubellmio.ResourceSummary), b.(*ResourceSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*url.Values)(nil), (*ClusterProxyOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_url_Values_To_v1alpha1_ClusterProxyOptions(a.(*url.Values), b.(*ClusterProxyOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_APIEnablement_To_clusterkubellmio_APIEnablement(in *APIEnablement, out *clusterkubellmio.APIEnablement, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Resources = *(*[]clusterkubellmio.APIResource)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha1_APIEnablement_To_clusterkubellmio_APIEnablement is an autogenerated conversion function.
func Convert_v1alpha1_APIEnablement_To_clusterkubellmio_APIEnablement(in *APIEnablement, out *clusterkubellmio.APIEnablement, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIEnablement_To_clusterkubellmio_APIEnablement(in, out, s)
}

func autoConvert_clusterkubellmio_APIEnablement_To_v1alpha1_APIEnablement(in *clusterkubellmio.APIEnablement, out *APIEnablement, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Resources = *(*[]APIResource)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_clusterkubellmio_APIEnablement_To_v1alpha1_APIEnablement is an autogenerated conversion function.
func Convert_clusterkubellmio_APIEnablement_To_v1alpha1_APIEnablement(in *clusterkubellmio.APIEnablement, out *APIEnablement, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_APIEnablement_To_v1alpha1_APIEnablement(in, out, s)
}

func autoConvert_v1alpha1_APIResource_To_clusterkubellmio_APIResource(in *APIResource, out *clusterkubellmio.APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_v1alpha1_APIResource_To_clusterkubellmio_APIResource is an autogenerated conversion function.
func Convert_v1alpha1_APIResource_To_clusterkubellmio_APIResource(in *APIResource, out *clusterkubellmio.APIResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIResource_To_clusterkubellmio_APIResource(in, out, s)
}

func autoConvert_clusterkubellmio_APIResource_To_v1alpha1_APIResource(in *clusterkubellmio.APIResource, out *APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_clusterkubellmio_APIResource_To_v1alpha1_APIResource is an autogenerated conversion function.
func Convert_clusterkubellmio_APIResource_To_v1alpha1_APIResource(in *clusterkubellmio.APIResource, out *APIResource, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_APIResource_To_v1alpha1_APIResource(in, out, s)
}

func autoConvert_v1alpha1_AllocatableModeling_To_clusterkubellmio_AllocatableModeling(in *AllocatableModeling, out *clusterkubellmio.AllocatableModeling, s conversion.Scope) error {
	out.Grade = in.Grade
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_AllocatableModeling_To_clusterkubellmio_AllocatableModeling is an autogenerated conversion function.
func Convert_v1alpha1_AllocatableModeling_To_clusterkubellmio_AllocatableModeling(in *AllocatableModeling, out *clusterkubellmio.AllocatableModeling, s conversion.Scope) error {
	return autoConvert_v1alpha1_AllocatableModeling_To_clusterkubellmio_AllocatableModeling(in, out, s)
}

func autoConvert_clusterkubellmio_AllocatableModeling_To_v1alpha1_AllocatableModeling(in *clusterkubellmio.AllocatableModeling, out *AllocatableModeling, s conversion.Scope) error {
	out.Grade = in.Grade
	out.Count = in.Count
	return nil
}

// Convert_clusterkubellmio_AllocatableModeling_To_v1alpha1_AllocatableModeling is an autogenerated conversion function.
func Convert_clusterkubellmio_AllocatableModeling_To_v1alpha1_AllocatableModeling(in *clusterkubellmio.AllocatableModeling, out *AllocatableModeling, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_AllocatableModeling_To_v1alpha1_AllocatableModeling(in, out, s)
}

func autoConvert_v1alpha1_Cluster_To_clusterkubellmio_Cluster(in *Cluster, out *clusterkubellmio.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Cluster_To_clusterkubellmio_Cluster is an autogenerated conversion function.
func Convert_v1alpha1_Cluster_To_clusterkubellmio_Cluster(in *Cluster, out *clusterkubellmio.Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cluster_To_clusterkubellmio_Cluster(in, out, s)
}

func autoConvert_clusterkubellmio_Cluster_To_v1alpha1_Cluster(in *clusterkubellmio.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusterkubellmio_Cluster_To_v1alpha1_Cluster is an autogenerated conversion function.
func Convert_clusterkubellmio_Cluster_To_v1alpha1_Cluster(in *clusterkubellmio.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_Cluster_To_v1alpha1_Cluster(in, out, s)
}

func autoConvert_v1alpha1_ClusterList_To_clusterkubellmio_ClusterList(in *ClusterList, out *clusterkubellmio.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusterkubellmio.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterList_To_clusterkubellmio_ClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterList_To_clusterkubellmio_ClusterList(in *ClusterList, out *clusterkubellmio.ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterList_To_clusterkubellmio_ClusterList(in, out, s)
}

func autoConvert_clusterkubellmio_ClusterList_To_v1alpha1_ClusterList(in *clusterkubellmio.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusterkubellmio_ClusterList_To_v1alpha1_ClusterList is an autogenerated conversion function.
func Convert_clusterkubellmio_ClusterList_To_v1alpha1_ClusterList(in *clusterkubellmio.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ClusterList_To_v1alpha1_ClusterList(in, out, s)
}

func autoConvert_v1alpha1_ClusterProxyOptions_To_clusterkubellmio_ClusterProxyOptions(in *ClusterProxyOptions, out *clusterkubellmio.ClusterProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_ClusterProxyOptions_To_clusterkubellmio_ClusterProxyOptions is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProxyOptions_To_clusterkubellmio_ClusterProxyOptions(in *ClusterProxyOptions, out *clusterkubellmio.ClusterProxyOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProxyOptions_To_clusterkubellmio_ClusterProxyOptions(in, out, s)
}

func autoConvert_clusterkubellmio_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in *clusterkubellmio.ClusterProxyOptions, out *ClusterProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_clusterkubellmio_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions is an autogenerated conversion function.
func Convert_clusterkubellmio_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in *clusterkubellmio.ClusterProxyOptions, out *ClusterProxyOptions, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in, out, s)
}

func autoConvert_url_Values_To_v1alpha1_ClusterProxyOptions(in *url.Values, out *ClusterProxyOptions, s conversion.Scope) error {
	// WARNING: Field TypeMeta does not have json tag, skipping.

	if values, ok := map[string][]string(*in)["path"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_string(&values, &out.Path, s); err != nil {
			return err
		}
	} else {
		out.Path = ""
	}
	return nil
}

// Convert_url_Values_To_v1alpha1_ClusterProxyOptions is an autogenerated conversion function.
func Convert_url_Values_To_v1alpha1_ClusterProxyOptions(in *url.Values, out *ClusterProxyOptions, s conversion.Scope) error {
	return autoConvert_url_Values_To_v1alpha1_ClusterProxyOptions(in, out, s)
}

func autoConvert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec(in *ClusterSpec, out *clusterkubellmio.ClusterSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.DisplayName = in.DisplayName
	out.APIEndpoint = in.APIEndpoint
	out.SecretRef = (*clusterkubellmio.LocalSecretReference)(unsafe.Pointer(in.SecretRef))
	out.ImpersonatorSecretRef = (*clusterkubellmio.LocalSecretReference)(unsafe.Pointer(in.ImpersonatorSecretRef))
	out.InsecureSkipTLSVerification = in.InsecureSkipTLSVerification
	out.ProxyURL = in.ProxyURL
	out.ProxyHeader = *(*map[string]string)(unsafe.Pointer(&in.ProxyHeader))
	out.Provider = in.Provider
	out.Region = in.Region
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	out.ResourceModels = *(*[]clusterkubellmio.ResourceModel)(unsafe.Pointer(&in.ResourceModels))
	return nil
}

// Convert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec(in *ClusterSpec, out *clusterkubellmio.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSpec_To_clusterkubellmio_ClusterSpec(in, out, s)
}

func autoConvert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec(in *clusterkubellmio.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.DisplayName = in.DisplayName
	out.APIEndpoint = in.APIEndpoint
	out.SecretRef = (*LocalSecretReference)(unsafe.Pointer(in.SecretRef))
	out.ImpersonatorSecretRef = (*LocalSecretReference)(unsafe.Pointer(in.ImpersonatorSecretRef))
	out.InsecureSkipTLSVerification = in.InsecureSkipTLSVerification
	out.ProxyURL = in.ProxyURL
	out.ProxyHeader = *(*map[string]string)(unsafe.Pointer(&in.ProxyHeader))
	out.Provider = in.Provider
	out.Region = in.Region
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	out.ResourceModels = *(*[]ResourceModel)(unsafe.Pointer(&in.ResourceModels))
	return nil
}

// Convert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec is an autogenerated conversion function.
func Convert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec(in *clusterkubellmio.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ClusterSpec_To_v1alpha1_ClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus(in *ClusterStatus, out *clusterkubellmio.ClusterStatus, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.APIEnablements = *(*[]clusterkubellmio.APIEnablement)(unsafe.Pointer(&in.APIEnablements))
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.NodeSummary = (*clusterkubellmio.NodeSummary)(unsafe.Pointer(in.NodeSummary))
	out.ResourceSummary = (*clusterkubellmio.ResourceSummary)(unsafe.Pointer(in.ResourceSummary))
	out.RemedyActions = *(*[]string)(unsafe.Pointer(&in.RemedyActions))
	return nil
}

// Convert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus(in *ClusterStatus, out *clusterkubellmio.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterStatus_To_clusterkubellmio_ClusterStatus(in, out, s)
}

func autoConvert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus(in *clusterkubellmio.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.APIEnablements = *(*[]APIEnablement)(unsafe.Pointer(&in.APIEnablements))
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.NodeSummary = (*NodeSummary)(unsafe.Pointer(in.NodeSummary))
	out.ResourceSummary = (*ResourceSummary)(unsafe.Pointer(in.ResourceSummary))
	out.RemedyActions = *(*[]string)(unsafe.Pointer(&in.RemedyActions))
	return nil
}

// Convert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus is an autogenerated conversion function.
func Convert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus(in *clusterkubellmio.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ClusterStatus_To_v1alpha1_ClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_LocalSecretReference_To_clusterkubellmio_LocalSecretReference(in *LocalSecretReference, out *clusterkubellmio.LocalSecretReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_LocalSecretReference_To_clusterkubellmio_LocalSecretReference is an autogenerated conversion function.
func Convert_v1alpha1_LocalSecretReference_To_clusterkubellmio_LocalSecretReference(in *LocalSecretReference, out *clusterkubellmio.LocalSecretReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_LocalSecretReference_To_clusterkubellmio_LocalSecretReference(in, out, s)
}

func autoConvert_clusterkubellmio_LocalSecretReference_To_v1alpha1_LocalSecretReference(in *clusterkubellmio.LocalSecretReference, out *LocalSecretReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_clusterkubellmio_LocalSecretReference_To_v1alpha1_LocalSecretReference is an autogenerated conversion function.
func Convert_clusterkubellmio_LocalSecretReference_To_v1alpha1_LocalSecretReference(in *clusterkubellmio.LocalSecretReference, out *LocalSecretReference, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_LocalSecretReference_To_v1alpha1_LocalSecretReference(in, out, s)
}

func autoConvert_v1alpha1_NodeSummary_To_clusterkubellmio_NodeSummary(in *NodeSummary, out *clusterkubellmio.NodeSummary, s conversion.Scope) error {
	out.TotalNum = in.TotalNum
	out.ReadyNum = in.ReadyNum
	return nil
}

// Convert_v1alpha1_NodeSummary_To_clusterkubellmio_NodeSummary is an autogenerated conversion function.
func Convert_v1alpha1_NodeSummary_To_clusterkubellmio_NodeSummary(in *NodeSummary, out *clusterkubellmio.NodeSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeSummary_To_clusterkubellmio_NodeSummary(in, out, s)
}

func autoConvert_clusterkubellmio_NodeSummary_To_v1alpha1_NodeSummary(in *clusterkubellmio.NodeSummary, out *NodeSummary, s conversion.Scope) error {
	out.TotalNum = in.TotalNum
	out.ReadyNum = in.ReadyNum
	return nil
}

// Convert_clusterkubellmio_NodeSummary_To_v1alpha1_NodeSummary is an autogenerated conversion function.
func Convert_clusterkubellmio_NodeSummary_To_v1alpha1_NodeSummary(in *clusterkubellmio.NodeSummary, out *NodeSummary, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_NodeSummary_To_v1alpha1_NodeSummary(in, out, s)
}

func autoConvert_v1alpha1_ResourceModel_To_clusterkubellmio_ResourceModel(in *ResourceModel, out *clusterkubellmio.ResourceModel, s conversion.Scope) error {
	out.Grade = in.Grade
	out.Ranges = *(*[]clusterkubellmio.ResourceModelRange)(unsafe.Pointer(&in.Ranges))
	return nil
}

// Convert_v1alpha1_ResourceModel_To_clusterkubellmio_ResourceModel is an autogenerated conversion function.
func Convert_v1alpha1_ResourceModel_To_clusterkubellmio_ResourceModel(in *ResourceModel, out *clusterkubellmio.ResourceModel, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceModel_To_clusterkubellmio_ResourceModel(in, out, s)
}

func autoConvert_clusterkubellmio_ResourceModel_To_v1alpha1_ResourceModel(in *clusterkubellmio.ResourceModel, out *ResourceModel, s conversion.Scope) error {
	out.Grade = in.Grade
	out.Ranges = *(*[]ResourceModelRange)(unsafe.Pointer(&in.Ranges))
	return nil
}

// Convert_clusterkubellmio_ResourceModel_To_v1alpha1_ResourceModel is an autogenerated conversion function.
func Convert_clusterkubellmio_ResourceModel_To_v1alpha1_ResourceModel(in *clusterkubellmio.ResourceModel, out *ResourceModel, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ResourceModel_To_v1alpha1_ResourceModel(in, out, s)
}

func autoConvert_v1alpha1_ResourceModelRange_To_clusterkubellmio_ResourceModelRange(in *ResourceModelRange, out *clusterkubellmio.ResourceModelRange, s conversion.Scope) error {
	out.Name = v1.ResourceName(in.Name)
	out.Min = in.Min
	out.Max = in.Max
	return nil
}

// Convert_v1alpha1_ResourceModelRange_To_clusterkubellmio_ResourceModelRange is an autogenerated conversion function.
func Convert_v1alpha1_ResourceModelRange_To_clusterkubellmio_ResourceModelRange(in *ResourceModelRange, out *clusterkubellmio.ResourceModelRange, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceModelRange_To_clusterkubellmio_ResourceModelRange(in, out, s)
}

func autoConvert_clusterkubellmio_ResourceModelRange_To_v1alpha1_ResourceModelRange(in *clusterkubellmio.ResourceModelRange, out *ResourceModelRange, s conversion.Scope) error {
	out.Name = v1.ResourceName(in.Name)
	out.Min = in.Min
	out.Max = in.Max
	return nil
}

// Convert_clusterkubellmio_ResourceModelRange_To_v1alpha1_ResourceModelRange is an autogenerated conversion function.
func Convert_clusterkubellmio_ResourceModelRange_To_v1alpha1_ResourceModelRange(in *clusterkubellmio.ResourceModelRange, out *ResourceModelRange, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ResourceModelRange_To_v1alpha1_ResourceModelRange(in, out, s)
}

func autoConvert_v1alpha1_ResourceSummary_To_clusterkubellmio_ResourceSummary(in *ResourceSummary, out *clusterkubellmio.ResourceSummary, s conversion.Scope) error {
	out.Allocatable = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Allocating = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocating))
	out.Allocated = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocated))
	out.AllocatableModelings = *(*[]clusterkubellmio.AllocatableModeling)(unsafe.Pointer(&in.AllocatableModelings))
	return nil
}

// Convert_v1alpha1_ResourceSummary_To_clusterkubellmio_ResourceSummary is an autogenerated conversion function.
func Convert_v1alpha1_ResourceSummary_To_clusterkubellmio_ResourceSummary(in *ResourceSummary, out *clusterkubellmio.ResourceSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceSummary_To_clusterkubellmio_ResourceSummary(in, out, s)
}

func autoConvert_clusterkubellmio_ResourceSummary_To_v1alpha1_ResourceSummary(in *clusterkubellmio.ResourceSummary, out *ResourceSummary, s conversion.Scope) error {
	out.Allocatable = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Allocating = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocating))
	out.Allocated = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocated))
	out.AllocatableModelings = *(*[]AllocatableModeling)(unsafe.Pointer(&in.AllocatableModelings))
	return nil
}

// Convert_clusterkubellmio_ResourceSummary_To_v1alpha1_ResourceSummary is an autogenerated conversion function.
func Convert_clusterkubellmio_ResourceSummary_To_v1alpha1_ResourceSummary(in *clusterkubellmio.ResourceSummary, out *ResourceSummary, s conversion.Scope) error {
	return autoConvert_clusterkubellmio_ResourceSummary_To_v1alpha1_ResourceSummary(in, out, s)
}
