//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 The Kubellm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	iamkubellmio "github.com/kubellm-io/kubellm/pkg/apis/iam.kubellm.io"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*User)(nil), (*iamkubellmio.User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_User_To_iamkubellmio_User(a.(*User), b.(*iamkubellmio.User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*iamkubellmio.User)(nil), (*User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_iamkubellmio_User_To_v1alpha1_User(a.(*iamkubellmio.User), b.(*User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserList)(nil), (*iamkubellmio.UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserList_To_iamkubellmio_UserList(a.(*UserList), b.(*iamkubellmio.UserList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*iamkubellmio.UserList)(nil), (*UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_iamkubellmio_UserList_To_v1alpha1_UserList(a.(*iamkubellmio.UserList), b.(*UserList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserSpec)(nil), (*iamkubellmio.UserSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec(a.(*UserSpec), b.(*iamkubellmio.UserSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*iamkubellmio.UserSpec)(nil), (*UserSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec(a.(*iamkubellmio.UserSpec), b.(*UserSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserStatus)(nil), (*iamkubellmio.UserStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus(a.(*UserStatus), b.(*iamkubellmio.UserStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*iamkubellmio.UserStatus)(nil), (*UserStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus(a.(*iamkubellmio.UserStatus), b.(*UserStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_User_To_iamkubellmio_User(in *User, out *iamkubellmio.User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_User_To_iamkubellmio_User is an autogenerated conversion function.
func Convert_v1alpha1_User_To_iamkubellmio_User(in *User, out *iamkubellmio.User, s conversion.Scope) error {
	return autoConvert_v1alpha1_User_To_iamkubellmio_User(in, out, s)
}

func autoConvert_iamkubellmio_User_To_v1alpha1_User(in *iamkubellmio.User, out *User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_iamkubellmio_User_To_v1alpha1_User is an autogenerated conversion function.
func Convert_iamkubellmio_User_To_v1alpha1_User(in *iamkubellmio.User, out *User, s conversion.Scope) error {
	return autoConvert_iamkubellmio_User_To_v1alpha1_User(in, out, s)
}

func autoConvert_v1alpha1_UserList_To_iamkubellmio_UserList(in *UserList, out *iamkubellmio.UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]iamkubellmio.User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_UserList_To_iamkubellmio_UserList is an autogenerated conversion function.
func Convert_v1alpha1_UserList_To_iamkubellmio_UserList(in *UserList, out *iamkubellmio.UserList, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserList_To_iamkubellmio_UserList(in, out, s)
}

func autoConvert_iamkubellmio_UserList_To_v1alpha1_UserList(in *iamkubellmio.UserList, out *UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_iamkubellmio_UserList_To_v1alpha1_UserList is an autogenerated conversion function.
func Convert_iamkubellmio_UserList_To_v1alpha1_UserList(in *iamkubellmio.UserList, out *UserList, s conversion.Scope) error {
	return autoConvert_iamkubellmio_UserList_To_v1alpha1_UserList(in, out, s)
}

func autoConvert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec(in *UserSpec, out *iamkubellmio.UserSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Email = in.Email
	out.Password = in.Password
	out.Lang = in.Lang
	out.Description = in.Description
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.PhoneNumber = in.PhoneNumber
	out.Avatar = in.Avatar
	out.Department = in.Department
	out.Position = in.Position
	out.ExternalID = in.ExternalID
	out.IdentityProvider = in.IdentityProvider
	out.LoginDisabled = (*bool)(unsafe.Pointer(in.LoginDisabled))
	return nil
}

// Convert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec is an autogenerated conversion function.
func Convert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec(in *UserSpec, out *iamkubellmio.UserSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserSpec_To_iamkubellmio_UserSpec(in, out, s)
}

func autoConvert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec(in *iamkubellmio.UserSpec, out *UserSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Email = in.Email
	out.Password = in.Password
	out.Lang = in.Lang
	out.Description = in.Description
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.PhoneNumber = in.PhoneNumber
	out.Avatar = in.Avatar
	out.Department = in.Department
	out.Position = in.Position
	out.ExternalID = in.ExternalID
	out.IdentityProvider = in.IdentityProvider
	out.LoginDisabled = (*bool)(unsafe.Pointer(in.LoginDisabled))
	return nil
}

// Convert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec is an autogenerated conversion function.
func Convert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec(in *iamkubellmio.UserSpec, out *UserSpec, s conversion.Scope) error {
	return autoConvert_iamkubellmio_UserSpec_To_v1alpha1_UserSpec(in, out, s)
}

func autoConvert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus(in *UserStatus, out *iamkubellmio.UserStatus, s conversion.Scope) error {
	out.State = iamkubellmio.UserState(in.State)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = (*v1.Time)(unsafe.Pointer(in.LastTransitionTime))
	out.LastLoginTime = (*v1.Time)(unsafe.Pointer(in.LastLoginTime))
	out.LastLoginIP = in.LastLoginIP
	out.FailedLoginAttempts = (*int32)(unsafe.Pointer(in.FailedLoginAttempts))
	out.PasswordExpiryTime = (*v1.Time)(unsafe.Pointer(in.PasswordExpiryTime))
	out.PasswordLastChangedTime = (*v1.Time)(unsafe.Pointer(in.PasswordLastChangedTime))
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus is an autogenerated conversion function.
func Convert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus(in *UserStatus, out *iamkubellmio.UserStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserStatus_To_iamkubellmio_UserStatus(in, out, s)
}

func autoConvert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus(in *iamkubellmio.UserStatus, out *UserStatus, s conversion.Scope) error {
	out.State = UserState(in.State)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = (*v1.Time)(unsafe.Pointer(in.LastTransitionTime))
	out.LastLoginTime = (*v1.Time)(unsafe.Pointer(in.LastLoginTime))
	out.LastLoginIP = in.LastLoginIP
	out.FailedLoginAttempts = (*int32)(unsafe.Pointer(in.FailedLoginAttempts))
	out.PasswordExpiryTime = (*v1.Time)(unsafe.Pointer(in.PasswordExpiryTime))
	out.PasswordLastChangedTime = (*v1.Time)(unsafe.Pointer(in.PasswordLastChangedTime))
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus is an autogenerated conversion function.
func Convert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus(in *iamkubellmio.UserStatus, out *UserStatus, s conversion.Scope) error {
	return autoConvert_iamkubellmio_UserStatus_To_v1alpha1_UserStatus(in, out, s)
}
